fix: Remove webpack import, use webpack from Next.js config params
Fixed TypeScript error: 'Cannot find module webpack'

Webpack is already available as a parameter in the Next.js webpack config function.
Changed from:
  import webpack from 'webpack'
  webpack: (config, { isServer }) => { ... }

To:
  webpack: (config, { isServer, webpack }) => { ... }

This avoids needing webpack as a dependency.